services:
  db:
    image: chromadb/chroma
    volumes:
      - chroma_data:/data
    ports:
      - "8000:8000"
    expose:
      - 8000
    # networks:
    #   - internal

  app:
    build: .
    env_file: .env
    depends_on:
      - db
    volumes: 
      - ./:/src
    ports:
      - "8080:8080"
    stdin_open: true 
    tty: true        
    restart: on-failure
    # networks:
    #   - internal

# networks:
#   internal:

volumes:
  chroma_data:
  
