services:
  db:
    container_name: pdf-helper-db
    image: chromadb/chroma
    volumes:
      - chroma_data:/data
    ports:
      - "8000:8000"
    # expose:
    #   - 8000

  app:
    container_name: pdf-helper-app
    build: .
    env_file: .env
    depends_on:
      - db
    volumes: 
      - ./app:/app
    ports:
      - "8080:8080"
    stdin_open: true 
    tty: true        
    restart: on-failure

volumes:
  chroma_data:
  
